### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [leonardfx/prj-rev-bwfs-dasmoto#5]
Grade: Meets expectations

Summary:
Great job on this project! I love your easy to read HTML your concise CSS.  

A few things to work on here would be: 1. keeping your files as modular as possible by avoiding inline-styles in your HTML, 2. using locally stored images with descriptive `alt` attributes for your `<img>` elements, and 3. using group selectors for any repeated styles in your CSS.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page totally responsive for all screen widths. This is a challenge I think you are ready for based on your work here! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by leonardfx-zz** [comment]
Thanks the detailed feedback!
